Eczamen/Eczamen/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Eczamen.Entitie;
using Eczamen.Models;
using Eczamen.Models.Utility;
using Eczamen.Repositories.interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures.Internal;

namespace Eczamen.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository icategoryRepository;

        public CategoryController(ICategoryRepository icategoryRepository)
        {
            this.icategoryRepository = icategoryRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await icategoryRepository.GetAllCategory());
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] CategoryModel category)
        {
            if (ModelState.IsValid)
            {
                if (!await icategoryRepository.CreateCategory(category))
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            CategoryModel model = await icategoryRepository.EditGetCategory(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id, Name")] CategoryModel model)
        {
            if (ModelState.IsValid)
            {
                if (!await icategoryRepository.EditPostCategory(model))
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            CategoryModel model = await icategoryRepository.EditGetCategory(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([Bind("Id, Name")] CategoryModel model)
        {
            
            if (!await icategoryRepository.DeleteCategory(model))
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            CategoryModel model = await icategoryRepository.EditGetCategory(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }
    }
}

Eczamen/Eczamen/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Eczamen.Entitie;
using Eczamen.Models.Utility;
using Eczamen.Repositories.interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Eczamen.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ICouponRepository iCouponRepository;

        public CouponController(ICouponRepository iCouponRepository)
        {
            this.iCouponRepository = iCouponRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await iCouponRepository.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupon)
        {
            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Form.Files;
                if (!await iCouponRepository.CreateCouponPost(file, coupon))
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(coupon);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            Coupon coupon = await iCouponRepository.EditCouponGet(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Coupon model)
        {
            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Form.Files;
                if (!await iCouponRepository.EditCouponPost(file, model))
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            Coupon coupon = await iCouponRepository.DeleteCouponGet(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Coupon coupon)
        {
            if (!await iCouponRepository.DeleteCoupon(coupon))
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            Coupon coupon = await iCouponRepository.DeleteCouponGet(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }
    }
}

Eczamen/Eczamen/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Eczamen.AppContext;
using Eczamen.Entitie.AplicUser;
using Eczamen.Models.Utility;
using Eczamen.Repositories.ManagerUsers.interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Eczamen.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class UsersController : Controller
    {
        private readonly IWorkUsersContext iContext;

        public UsersController( IWorkUsersContext iContext)
        {
            this.iContext = iContext;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(await iContext.GetAllUsers(claim));
        }

        public async Task<IActionResult> Lock(string id)
        {
            if (!await iContext.LockUser(id))
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> UnLock(string id)
        {
            if (!await iContext.UnLockUser(id))
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Eczamen/Eczamen/Areas/Customer/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Eczamen.Models;
using Eczamen.Models.Utility;
using Eczamen.Repositories.interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Eczamen.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IShoppingCartRepository _iShoppingCartRepository;
        private readonly IOrderHeaderRepository _iOrderHeaderRepository;
        private readonly IOrderDetailsRepository _iOrderDetailsRepository;
        private readonly IMenuItemRepository _menuItemRepository;
        private readonly ICouponRepository _couponRepository;
        [BindProperty]
        public OrderDetailsCart OrderDetailsCart { get; set; }

        public CartController(IShoppingCartRepository iShoppingCartRepository, IOrderHeaderRepository iOrderHeaderRepository,
            IOrderDetailsRepository iOrderDetailsRepository, IMenuItemRepository menuItemRepository, ICouponRepository couponRepository)
        {
            _iShoppingCartRepository = iShoppingCartRepository;
            _iOrderHeaderRepository = iOrderHeaderRepository;
            _iOrderDetailsRepository = iOrderDetailsRepository;
            _menuItemRepository = menuItemRepository;
            _couponRepository = couponRepository;
        }

        public async Task<IActionResult> Index()
        {
            Claim claimIdentity = GetClaim();
            string code = HttpContext.Session.GetString(SD.ssCuponCode);
            this.OrderDetailsCart =
                await _iShoppingCartRepository.GetOrderDetailsCart(claimIdentity, _menuItemRepository, code, _couponRepository);
            return View(this.OrderDetailsCart);
        }

        private Claim GetClaim()
        {
            var claimUser = (ClaimsIdentity) this.User.Identity;
            return claimUser.FindFirst(ClaimTypes.NameIdentifier);
        }

        public IActionResult AddCoupon()
        {
            if (OrderDetailsCart.OrderHeader.CouponCode == null)
            {
                this.OrderDetailsCart.OrderHeader.CouponCode = "";
            }
            HttpContext.Session.SetString(SD.ssCuponCode, OrderDetailsCart.OrderHeader.CouponCode);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveCoupon()
        {
            HttpContext.Session.SetString(SD.ssCuponCode, "");
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Plus(int cartId)
        {
            if (!await _iShoppingCartRepository.PlusCartRepository(cartId))
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Minus(int cartId)
        {
            var cart = await _iShoppingCartRepository.AllItems.FirstOrDefaultAsync(z => z.Id == cartId);
            if (cart.Count == 1)
            {
                _iShoppingCartRepository.Context.Remove(cart);
                await _iShoppingCartRepository.Context.SaveChangesAsync();
                var cnt = _iShoppingCartRepository.AllItems.Where(x => x.ApplicationUserId == cart.ApplicationUserId)
                    .ToList().Count;
                HttpContext.Session.SetInt32(SD.ssShoppingCartCount, cnt);
            }
            else
            {
                if (!await _iShoppingCartRepository.MinusCartRepository(cartId))
                {
                    return NotFound();
                }
            }
            
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Remove(int cartId)
        {
            var cart = await _iShoppingCartRepository.AllItems.FirstOrDefaultAsync(z => z.Id == cartId);
            _iShoppingCartRepository.Context.Remove(cart);
            await _iShoppingCartRepository.SaveChangesAsync();
            var cnt = _iShoppingCartRepository.AllItems.Where(x => x.ApplicationUserId == cart.ApplicationUserId)
                .ToList().Count;
            HttpContext.Session.SetInt32(SD.ssShoppingCartCount, cnt);

            return RedirectToAction(nameof(Index));
        }
    }
}

Eczamen/Eczamen/Views/Shared/_BacToEditButtonPartial.cshtml
@model int
<p><a asp-action="Edit" asp-route-id="@Model" class="btn btn-primary form-control">Edit</a></p>

Eczamen/Eczamen/Views/Shared/_BacToListButtonPartial.cshtml
<p><a asp-action="Index" class="btn btn-success form-control">Back to List</a></p>

Eczamen/Eczamen/Views/Shared/_CreateButtonPartial.cshtml
<p><a class="btn btn-primary" asp-action="Create"><i class="fas fa-plus"></i>&nbsp;  Create New</a></p>

Eczamen/Eczamen/Views/Shared/_CreateButtonPostPartial.cshtml
<p><input type="submit" value="Create" class="btn btn-primary form-control" /></p>

Eczamen/Eczamen/Views/Shared/_DeleteButtonPartial.cshtml
<p><input type="submit" value="Delete" class="btn btn-danger form-control" /></p>

Eczamen/Eczamen/Views/Shared/_EditButtonPartial.cshtml
<p><input type="submit" value="Update" class="btn btn-primary form-control" /></p>

Eczamen/Eczamen/Views/Shared/_Layout.cshtml
@using Eczamen.Models.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oleg</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="~/images/mild.png" />
                    <img src="~/images/spicy.png" />
                    <img src="~/images/veryspicy.png" />
                    <label class="text-info" style="cursor: pointer">Oleg</label> 
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item text-white-50 dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="DropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="False">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="DropDownMenuLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">MenuItem</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Coupons</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Users" asp-area="Admin">Users</a>
                                </div>
                            </li>
                        }
                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCartCount) != null)
                        {
                            <li style="color: white">
                                @{
                                    var count = HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCartCount);
                                }
                                <a asp-area="Customer" asp-action="Index" asp-controller="Cart" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color:white">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer pl-3 text-muted text-white-50" style="background-color: #343a40">
        <div class="container">
            &copy; 2019 - Oleg Pletinenko
        </div>
    </footer>

    <environment include="Development">
        <script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=3svgeehxs84icdlingw9tup3iht7qcjezbs8plmml5qq6o3m"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=3svgeehxs84icdlingw9tup3iht7qcjezbs8plmml5qq6o3m"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Eczamen/Eczamen/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Eczamen/Eczamen/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width: 150px">
    <div class="btn-group" role="group">
        <a asp-action="Edit" asp-route-Id="@Model" class="btn btn-primary text-white"><i class="fas fa-edit"></i></a>
        <a asp-action="Details" asp-route-Id="@Model" class="btn btn-success text-white"><i class="fas fa-list-alt"></i></a>
        <a asp-action="Delete" asp-route-Id="@Model" class="btn btn-danger text-white"><i class="fas fa-trash-alt"></i></a>
    </div>
</td>

Eczamen/Eczamen/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<Eczamen.Entitie.MenuItem>


@if (Model.ToList().Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().SubCategory.Category.NameCategory.Replace(" ",string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success"> @Model.FirstOrDefault().SubCategory.Category.NameCategory </h3>
        </div>
        @foreach (var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px;color:maroon">@item.Name</label>
                                @if (item.Spicyness == "1")
                                {
                                    <img srcset="/images/mild.png" title="Mild" />
                                }
                                @if (item.Spicyness == "2")
                                {
                                    <img srcset="/images/spicy.png" title="Spicy" />
                                }
                                @if (item.Spicyness == "3")
                                {
                                    <img srcset="/images/veryspicy.png" title="Very Spicy" />
                                }
                                    <div class="mt-1 mb-1">
                                        <label class="badge badge-info">@item.SubCategory.NameSubCategory</label>
                                    </div>
                            </div>
                            <div class="col-4 text-right" style="color:maroon">
                                <h4>$@item.Price</h4>
                            </div>
                        </div>

                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Details</a>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="p-4"></div>
    </div>
}